spring.application.name=purchaseTransaction

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wexinc

spring.datasource.username=user
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debug
logging.level.reactor.netty.http.client.HttpClient=DEBUG
logging.level.web=DEBUG

# URIs
fiscal.api.base-url=https://api.fiscaldata.treasury.gov/services/api/fiscal_service